# Generated by Django 3.0.8 on 2020-07-13 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='last_update',
            field=models.DateField(auto_now=True),
        ),
    ]
