# Generated by Django 3.0.6 on 2020-05-18 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200518_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='creation',
        ),
    ]
