# Generated by Django 3.0.7 on 2020-06-26 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name=models.BooleanField(default=False, verbose_name='active')),
            preserve_default=False,
        ),
    ]
