# Generated by Django 3.0.8 on 2020-07-03 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20200629_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='NoName', max_length=30, verbose_name='name'),
        ),
    ]
