# Generated by Django 3.0.7 on 2020-07-01 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globaltag',
            name='title',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='localtag',
            name='title',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
