# Generated by Django 3.0.6 on 2020-05-22 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Photo',
            new_name='PostPhoto',
        ),
    ]
