# Generated by Django 3.0.6 on 2020-05-25 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20200522_2034'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostPhoto',
            new_name='ItemPhoto',
        ),
    ]
