# Generated by Django 3.0.6 on 2020-05-25 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20200525_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemphoto',
            name='image',
            field=models.ImageField(upload_to='media/item_photos'),
        ),
    ]
