# Generated by Django 3.0.6 on 2020-05-25 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20200525_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemphoto',
            name='image',
            field=models.ImageField(upload_to='item_photos'),
        ),
    ]
