# Generated by Django 3.0.6 on 2020-05-27 15:55

from django.db import migrations, models
import time


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_item_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(default=time.time),
        ),
    ]
