# Generated by Django 3.0.6 on 2020-05-30 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_item_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemphoto',
            name='image',
            field=models.ImageField(default='default_item_photo.jpg', upload_to='item_photos'),
        ),
    ]
