# Generated by Django 3.0.6 on 2020-06-04 18:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_auto_20200601_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='date_upd',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
