# Generated by Django 3.0.6 on 2020-06-11 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_auto_20200611_1449'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='tags',
            new_name='tag',
        ),
    ]
