# Generated by Django 3.0.6 on 2020-06-12 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_auto_20200611_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globaltag',
            name='description',
        ),
        migrations.RemoveField(
            model_name='localtag',
            name='description',
        ),
    ]
